# Generated by Django 4.1.4 on 2023-02-20 12:29

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='headset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=1000)),
                ('headset_head', models.CharField(max_length=200)),
                ('headset_discount_price', models.CharField(max_length=10)),
                ('headset_orginal_price', models.CharField(max_length=10)),
                ('headset_discount', models.CharField(max_length=10)),
                ('headset_integer_dicount', models.IntegerField()),
                ('headset_integer_orginal', models.IntegerField()),
                ('headset_users', models.CharField(max_length=30)),
                ('headset_color', models.CharField(max_length=100)),
                ('headset_brand', models.CharField(default='brand', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=1000)),
                ('head', models.CharField(max_length=200)),
                ('discount_price', models.CharField(max_length=10)),
                ('orginal_price', models.CharField(max_length=10)),
                ('discount', models.CharField(max_length=10)),
                ('int_dicount_price', models.IntegerField()),
                ('int_orginal_price', models.IntegerField()),
                ('users', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=100)),
                ('brand', models.CharField(default='brand', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Mobile_depth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
                ('head', models.TextField(default='head', max_length=500)),
                ('discount', models.CharField(max_length=20)),
                ('orginal_price', models.CharField(default='1', max_length=10)),
                ('discount_price', models.CharField(default='1', max_length=10)),
                ('rating_img', models.ImageField(default='pics', upload_to='pics')),
                ('day', models.CharField(default='10', max_length=10)),
                ('date', models.IntegerField(default=1)),
                ('users', models.CharField(default=1, max_length=40)),
                ('int_discount_price', models.IntegerField(default='10')),
                ('int_orginal_price', models.IntegerField(blank=True, default='10', null=True)),
                ('image', models.ImageField(default='image', upload_to='pics')),
                ('model_name', models.CharField(max_length=20)),
                ('retailer', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=10)),
                ('screen_size', models.CharField(default='mobile', max_length=50)),
                ('Camera_description', models.CharField(default='mobile', max_length=50)),
                ('screen_type', models.CharField(default='mob', max_length=50)),
                ('Battery', models.CharField(default='5000mah', max_length=50)),
                ('Ram', models.CharField(default='4Gb', max_length=400)),
                ('storage', models.CharField(default='2Gb', max_length=50)),
                ('os', models.CharField(default='12', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Shirts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=200)),
                ('shirt_head', models.CharField(max_length=200)),
                ('shirt_discount_price', models.CharField(max_length=10)),
                ('shirt_orginal_price', models.CharField(max_length=10)),
                ('shirt_discount', models.CharField(max_length=10)),
                ('shirt_integer_dicount', models.IntegerField()),
                ('shirt_integer_orginal', models.IntegerField()),
                ('shirt_model', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=400)),
                ('tv_head', models.CharField(max_length=200)),
                ('tv_discount_price', models.CharField(max_length=10)),
                ('tv_orginal_price', models.CharField(max_length=10)),
                ('tv_discount', models.CharField(max_length=10)),
                ('tv_integer_dicount', models.IntegerField()),
                ('tv_integer_orginal', models.IntegerField()),
                ('tv_users', models.CharField(max_length=30)),
                ('tv_warranty', models.CharField(max_length=500)),
                ('tv_screen', models.CharField(max_length=100)),
                ('tv_os', models.CharField(max_length=100, null=True)),
                ('tv_brand', models.CharField(default='brand', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User_Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='usermodel',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('mobile', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user', models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Cart_redirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=800)),
                ('head', models.CharField(max_length=400)),
                ('quantity', models.IntegerField()),
                ('size', models.CharField(max_length=100)),
                ('int_price', models.IntegerField()),
                ('str_price', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Browsing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='image', upload_to='pics')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
