# Generated by Django 4.1.4 on 2023-02-20 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='headset',
            old_name='headset_head',
            new_name='head',
        ),
    ]
