# Generated by Django 4.1.4 on 2023-02-20 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_rename_headset_head_headset_head'),
    ]

    operations = [
        migrations.RenameField(
            model_name='headset',
            old_name='headset_discount',
            new_name='discount',
        ),
        migrations.RenameField(
            model_name='headset',
            old_name='headset_discount_price',
            new_name='discount_price',
        ),
        migrations.RenameField(
            model_name='headset',
            old_name='headset_orginal_price',
            new_name='orginal_price',
        ),
    ]
