# Generated by Django 4.1.4 on 2023-02-20 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0003_rename_headset_discount_headset_discount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='headset',
            old_name='headset_brand',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='headset',
            old_name='headset_color',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='headset',
            old_name='headset_integer_dicount',
            new_name='int_dicount_price',
        ),
        migrations.RenameField(
            model_name='headset',
            old_name='headset_integer_orginal',
            new_name='int_orginal_price',
        ),
        migrations.RenameField(
            model_name='headset',
            old_name='headset_users',
            new_name='users',
        ),
    ]
