# Generated by Django 4.1.4 on 2023-02-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0004_rename_headset_brand_headset_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='headset',
            name='type',
            field=models.CharField(default='headset', max_length=10),
        ),
    ]
