# Generated by Django 4.1.4 on 2023-02-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0007_laptop_type_mobile_depth_type_shirts_type_tv_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='type',
            field=models.CharField(default='product', max_length=20),
        ),
    ]
