# Generated by Django 4.1.4 on 2023-02-20 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0009_rename_tv_discount_tv_discount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tv',
            old_name='tv_brand',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='tv',
            old_name='tv_os',
            new_name='os',
        ),
        migrations.RenameField(
            model_name='tv',
            old_name='tv_screen',
            new_name='screen',
        ),
        migrations.RenameField(
            model_name='tv',
            old_name='tv_users',
            new_name='users',
        ),
        migrations.RenameField(
            model_name='tv',
            old_name='tv_warranty',
            new_name='warranty',
        ),
    ]
