# Generated by Django 4.1.4 on 2023-02-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0011_rename_shirt_discount_shirts_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='head',
            field=models.CharField(default='main head', max_length=1000),
        ),
    ]
