# Generated by Django 4.1.4 on 2023-02-20 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0012_search_head'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='browsing',
            name='img',
        ),
    ]
