# Generated by Django 4.1.4 on 2023-02-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0013_remove_browsing_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='browsing',
            name='img',
            field=models.CharField(default='image', max_length=1000),
        ),
    ]
