# Generated by Django 4.1.4 on 2023-02-21 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0015_headset_date_headset_day_headset_rating_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='browsing',
            name='type',
            field=models.CharField(default='product', max_length=100),
        ),
    ]
