# Generated by Django 4.1.4 on 2023-02-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0017_mobile_depth_url_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='Ram',
            field=models.CharField(default='4Gb', max_length=400),
        ),
        migrations.AddField(
            model_name='laptop',
            name='os',
            field=models.CharField(default='12', max_length=50),
        ),
        migrations.AddField(
            model_name='laptop',
            name='processor',
            field=models.CharField(default='5000mah', max_length=50),
        ),
        migrations.AddField(
            model_name='laptop',
            name='screen_type',
            field=models.CharField(default='mob', max_length=50),
        ),
        migrations.AddField(
            model_name='laptop',
            name='storage',
            field=models.CharField(default='2Gb', max_length=50),
        ),
        migrations.AddField(
            model_name='laptop',
            name='warranty',
            field=models.CharField(default='warranty', max_length=100),
        ),
    ]
