# Generated by Django 4.1.4 on 2023-02-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0018_laptop_ram_laptop_os_laptop_processor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laptop',
            old_name='int_dicount_price',
            new_name='int_discount_price',
        ),
        migrations.AlterField(
            model_name='laptop',
            name='processor',
            field=models.CharField(default='5000mah', max_length=1000),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='warranty',
            field=models.CharField(default='warranty', max_length=1000),
        ),
    ]
