# Generated by Django 4.1.4 on 2023-02-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0019_rename_int_dicount_price_laptop_int_discount_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='os',
            field=models.CharField(default='12', max_length=150),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='storage',
            field=models.CharField(default='2Gb', max_length=450),
        ),
    ]
