# Generated by Django 4.1.4 on 2023-02-22 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0023_today_deals'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shirts',
            old_name='shirt_model',
            new_name='fashion_model',
        ),
        migrations.RenameField(
            model_name='womens_clothes',
            old_name='women_model',
            new_name='fashion_model',
        ),
    ]
