# Generated by Django 4.1.4 on 2023-02-24 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0026_shirts_users_womens_clothes_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='headset',
            old_name='int_dicount_price',
            new_name='int_discount_price',
        ),
        migrations.RenameField(
            model_name='shirts',
            old_name='int_dicount_price',
            new_name='int_discount_price',
        ),
        migrations.RenameField(
            model_name='tv',
            old_name='int_dicount_price',
            new_name='int_discount_price',
        ),
        migrations.RenameField(
            model_name='womens_clothes',
            old_name='int_dicount_price',
            new_name='int_discount_price',
        ),
    ]
