# Generated by Django 4.1.4 on 2023-02-26 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0030_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
