# Generated by Django 4.1.4 on 2023-02-26 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0032_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='score',
        ),
    ]
