# Generated by Django 4.1.4 on 2023-02-26 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0033_remove_rating_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='rating',
            name='review',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='rating',
            name='type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
