# Generated by Django 4.1.4 on 2023-02-27 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0034_rating_rating_rating_review_rating_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
