# Generated by Django 4.1.4 on 2023-02-27 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0036_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
