# Generated by Django 4.1.4 on 2023-02-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0039_buynow'),
    ]

    operations = [
        migrations.AddField(
            model_name='buynow',
            name='product_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
