# Generated by Django 4.1.4 on 2023-02-27 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0040_buynow_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buynow',
            name='product_id',
        ),
    ]
