# Generated by Django 4.1.4 on 2023-02-27 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0041_remove_buynow_product_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buynow',
        ),
    ]
